version: 0.2

env:
  variables:
    GIT_CLONE_DEPTH: 0
    AWS_DEFAULT_REGION: ${AWS_REGION}

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing AWS CLI..."
      - apt-get update && apt-get install -y awscli
      - aws --version

  pre_build:
    commands:
      - echo "Starting Web Deploy Phase..."
      - echo "Deploy started on $(date)"
      - echo "S3 Bucket - ${WEB_S3_BUCKET_NAME}"
      - echo "Verifying S3 bucket exists..."
      - aws s3 ls s3://${WEB_S3_BUCKET_NAME} || (echo "ERROR - S3 bucket ${WEB_S3_BUCKET_NAME} not found" && exit 1)
      - echo "✓ S3 bucket verified"

  build:
    commands:
      - echo "Deploying web application to S3..."
      - echo "Source directory - packages/web/dist"
      - ls -la packages/web/dist/ || (echo "ERROR - dist directory not found. Make sure build stage completed successfully." && exit 1)
      - echo "Syncing files to S3..."
      - aws s3 sync packages/web/dist/ s3://${WEB_S3_BUCKET_NAME}/ --delete --exact-timestamps
      - echo "✓ Files synced to S3"
      - echo "Setting cache control headers..."
      - |
        # Set cache headers for different file types
        aws s3 cp s3://${WEB_S3_BUCKET_NAME}/ s3://${WEB_S3_BUCKET_NAME}/ \
          --recursive \
          --exclude "*" \
          --include "*.html" \
          --cache-control "no-cache, no-store, must-revalidate" \
          --metadata-directive REPLACE || true
        aws s3 cp s3://${WEB_S3_BUCKET_NAME}/ s3://${WEB_S3_BUCKET_NAME}/ \
          --recursive \
          --exclude "*" \
          --include "*.js" \
          --include "*.css" \
          --cache-control "public, max-age=31536000, immutable" \
          --metadata-directive REPLACE || true
        aws s3 cp s3://${WEB_S3_BUCKET_NAME}/ s3://${WEB_S3_BUCKET_NAME}/ \
          --recursive \
          --exclude "*" \
          --include "*.png" \
          --include "*.jpg" \
          --include "*.jpeg" \
          --include "*.gif" \
          --include "*.svg" \
          --include "*.ico" \
          --cache-control "public, max-age=31536000, immutable" \
          --metadata-directive REPLACE || true
      - echo "✓ Cache headers set"
      - echo "Listing deployed files..."
      - aws s3 ls s3://${WEB_S3_BUCKET_NAME}/ --recursive | head -20

  post_build:
    commands:
      - echo "Post-deploy phase for Web..."
      - echo "Deployment completed on $(date)"
      - echo "S3 Bucket - ${WEB_S3_BUCKET_NAME}"
      - echo "✓ Web application deployed to S3 successfully"
      - echo "Note - CloudFront cache invalidation is not needed for immediate updates"

artifacts:
  files:
    - '**/*'
  name: web-deploy-artifact
