version: 0.2

env:
  variables:
    GIT_CLONE_DEPTH: 0
    AWS_DEFAULT_REGION: ${AWS_REGION}

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Docker and AWS CLI..."
      - yum install -y docker
      - service docker start
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - aws --version
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

  pre_build:
    commands:
      - echo "Starting Web Deploy Phase..."
      - echo "Deploy started on $(date)"
      - echo "Setting variables..."
      - ECR_REPOSITORY=${ECR_REPOSITORY_URI}
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - echo "ECR Repository: $ECR_REPOSITORY"
      - echo "Image Tag: $IMAGE_TAG"
      - echo "Building Docker image..."
      - cd packages/web
      - docker build --build-arg VITE_API_URL=${VITE_API_URL} -t $ECR_REPOSITORY:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REPOSITORY:latest
      - echo "Docker image built successfully"

  build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPOSITORY:$IMAGE_TAG
      - docker push $ECR_REPOSITORY:latest
      - echo "Image pushed to ECR successfully"
      - echo "Updating ECS service..."
      - aws ecs update-service \
          --cluster ${ECS_CLUSTER_NAME} \
          --service ${ECS_SERVICE_NAME} \
          --force-new-deployment \
          --region ${AWS_REGION}
      - echo "ECS service update initiated"
      - echo "Waiting for service to stabilize..."
      - aws ecs wait services-stable \
          --cluster ${ECS_CLUSTER_NAME} \
          --services ${ECS_SERVICE_NAME} \
          --region ${AWS_REGION}
      - echo "ECS service deployment completed successfully"

  post_build:
    commands:
      - echo "Post-deploy phase for Web..."
      - echo "Deployment completed on $(date)"
      - echo "Image: $ECR_REPOSITORY:$IMAGE_TAG"

artifacts:
  files:
    - '**/*'
  name: web-deploy-artifact

