version: 0.2

env:
  variables:
    GIT_CLONE_DEPTH: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing curl for health checks..."
      - apt-get update && apt-get install -y curl

  pre_build:
    commands:
      - echo "Starting Web Test Phase..."
      - echo "Test started on $(date)"
      - echo "Waiting for service to be ready..."
      - sleep 30

  build:
    commands:
      - echo "Testing Web frontend endpoint..."
      - export WEB_URL=${ALB_DNS_NAME}
      - echo "Web URL - $WEB_URL"
      - |
        export MAX_RETRIES=10
        export RETRY_COUNT=0
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          echo "Attempt $((RETRY_COUNT + 1)) of $MAX_RETRIES..."
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $WEB_URL || echo "000")
          echo "HTTP Status Code - $HTTP_CODE"
          
          if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "301" ] || [ "$HTTP_CODE" = "302" ]; then
            echo "✓ Web frontend is accessible!"
            exit 0
          fi
          
          RETRY_COUNT=$((RETRY_COUNT + 1))
          if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
            echo "Waiting 10 seconds before retry..."
            sleep 10
          fi
        done
        
        echo "✗ Web frontend check failed after $MAX_RETRIES attempts"
        exit 1

  post_build:
    commands:
      - echo "Post-test phase for Web..."
      - echo "Tests completed on $(date)"

artifacts:
  files:
    - '**/*'
  name: web-test-artifact

