version: 0.2

env:
  variables:
    GIT_CLONE_DEPTH: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing curl and jq for health checks..."
      - apt-get update && apt-get install -y curl jq

  pre_build:
    commands:
      - echo "Starting API Test Phase..."
      - echo "Test started on $(date)"
      - echo "Waiting for service to be ready (deployment may take several minutes)..."
      - sleep 60

  build:
    commands:
      - echo "Testing API health endpoint..."
      - export HEALTH_URL=${ALB_DNS_NAME}/api/health
      - echo "Health check URL - $HEALTH_URL"
      - |
        export MAX_RETRIES=20
        export RETRY_COUNT=0
        export RETRY_INTERVAL=15
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          echo "Attempt $((RETRY_COUNT + 1)) of $MAX_RETRIES..."
          
          # Get HTTP status code
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $HEALTH_URL 2>&1 || echo "000")
          echo "HTTP Status Code - $HTTP_CODE"
          
          # Get more details on error
          if [ "$HTTP_CODE" != "200" ]; then
            echo "Response details:"
            curl -v $HEALTH_URL 2>&1 | head -20 || echo "Could not connect to $HEALTH_URL"
            
            # Explain common error codes
            case "$HTTP_CODE" in
              "502")
                echo "⚠ 502 Bad Gateway: ALB cannot reach healthy targets. API service may still be deploying or containers may be unhealthy."
                ;;
              "503")
                echo "⚠ 503 Service Unavailable: API service is temporarily unavailable."
                ;;
              "504")
                echo "⚠ 504 Gateway Timeout: Request timed out."
                ;;
              "000")
                echo "⚠ Connection failed: Could not reach the endpoint."
                ;;
            esac
          fi
          
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✓ Health check passed!"
            echo "Health check response:"
            curl -s $HEALTH_URL | jq . || curl -s $HEALTH_URL
            echo ""
            echo "Response headers:"
            curl -s -I $HEALTH_URL | head -10
            exit 0
          fi
          
          RETRY_COUNT=$((RETRY_COUNT + 1))
          if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
            echo "Waiting $RETRY_INTERVAL seconds before retry..."
            sleep $RETRY_INTERVAL
          fi
        done
        
        echo "✗ Health check failed after $MAX_RETRIES attempts"
        echo "Last attempt details:"
        curl -v $HEALTH_URL 2>&1 | head -30
        echo ""
        echo "Possible issues:"
        echo "  - API service containers may not be running"
        echo "  - Health checks may be failing"
        echo "  - Service may still be deploying (check ECS service status)"
        echo "  - Target group may have no healthy targets"
        echo "  - Database connection may be failing"
        echo "  - API may be crashing on startup"
        exit 1

  post_build:
    commands:
      - echo "Post-test phase for API..."
      - echo "Tests completed on $(date)"

artifacts:
  files:
    - '**/*'
  name: api-test-artifact

