version: 0.2

env:
  variables:
    GIT_CLONE_DEPTH: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing phase..."
      - echo "Node $(node --version), npm $(npm --version)"

  pre_build:
    commands:
      - echo "Starting Web Build Phase..."
      - echo "Build started on $(date)"
      - echo "Current directory - $(pwd)"
      - echo "Listing root directory contents..."
      - ls -la
      - echo "Checking for packages/web directory..."
      - test -d packages/web || (echo "ERROR - packages/web/ NOT FOUND" && exit 1)
      - echo "✓ packages/web/ exists"
      - echo "Installing dependencies for Web..."
      - npm install --prefix packages/web --include=dev --legacy-peer-deps
      - echo "✓ Dependencies installed successfully"
      - echo "Verifying TypeScript installation..."
      - test -f packages/web/node_modules/.bin/tsc && echo "✓ tsc found" || (echo "ERROR - tsc not found" && exit 1)
      - echo "Verifying Vite installation..."
      - test -f packages/web/node_modules/.bin/vite && echo "✓ vite found" || (echo "ERROR - vite not found" && exit 1)

  build:
    commands:
      - echo "Building Web Application..."
      - echo "Running TypeScript compiler..."
      - cd packages/web && npx tsc -p tsconfig.json
      - echo "✓ TypeScript compilation completed"
      - echo "Running Vite build..."
      - cd packages/web && npx vite build
      - echo "✓ Vite build completed"
      - echo "Listing dist contents..."
      - ls -la packages/web/dist/
      - find packages/web/dist -type f | head -20
      - echo "✓ Web build completed successfully"

  post_build:
    commands:
      - echo "Post-build phase for Web..."
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: 'packages/web/dist'
  name: web-build-artifact

cache:
  paths:
    - 'packages/web/node_modules/**/*'
