version: 0.2

env:
  variables:
    GIT_CLONE_DEPTH: 0  # Forces full clone

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing phase..."
      - echo "Node $(node --version), NPM $(npm --version)"
      - echo "Forcing full git clone..."
      - git fetch --unshallow || true
      - git pull --unshallow || true
      - echo "Initializing submodules (if any)..."
      - git submodule update --init --recursive || true

  pre_build:
    commands:
      - echo "Installing deps..."
      - npm install --prefix packages/web --legacy-peer-deps
      - ls -la
      - echo "Verifying packages/api exists..."
      - test -d packages/api && echo "packages/api FOUND" || (echo "packages/api MISSING" && exit 1)
      - find . -maxdepth 2 -type d

      - echo "Installing API dependencies..."
      - npm install --prefix packages/api --legacy-peer-deps

      - echo "Generating Prisma client..."
      - ./packages/api/node_modules/.bin/prisma generate
      - echo "Prisma client generated"

  build:
    commands:
      - echo "Compiling TypeScript..."
      - ./packages/api/node_modules/.bin/tsc --project packages/api
      - echo "Build output:"
      - ls -la packages/api/dist/

  post_build:
    commands:
      - echo "API build completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: 'packages/api/dist'
  name: api-build-artifact-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - 'packages/api/node_modules/**/*'