version: 0.2

env:
  variables:
    GIT_CLONE_DEPTH: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Node $(node --version), npm $(npm --version)"
      - git fetch --unshallow || true
      - git submodule update --init --recursive || true

  pre_build:
    commands:
      - echo "Verifying packages/web exists..."
      - test -d packages/web 
      - ls -la packages/web/
      - echo "Installing dependencies..."
      - npm install --prefix packages/web --legacy-peer-deps
      - echo "Dependencies installed"

  build:
    commands:
      - echo "Compiling TypeScript..."
      - ./packages/web/node_modules/.bin/tsc --project packages/web
      - echo "Running Vite build..."
      - ./packages/web/node_modules/.bin/vite build
      - echo "Build complete. Listing dist/..."
      - ls -la packages/web/dist/

  post_build:
    commands:
      - echo "Web build completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: 'packages/web/dist'
  name: web-build-artifact-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - 'packages/web/node_modules/**/*'