version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting API Build Phase..."
      - echo "Build started on $(date)"
      - echo "Current directory - $(pwd)"
      - echo "Checking Node version..."
      - node --version
      - npm --version
      
  build:
    commands:
      - echo "Building API Application..."
      - cd packages/api
      - echo "Installing dependencies..."
      - npm ci --legacy-peer-deps || npm install --legacy-peer-deps
      - echo "Dependencies installed, verifying..."
      - ls -la node_modules/.bin/ | head -20
      - echo "Generating Prisma client..."
      - npx prisma generate
      - echo "Running build..."
      - npm run build
      - echo "Build completed, checking output..."
      - ls -la dist/
      - echo "API build completed successfully"
      
  post_build:
    commands:
      - echo "Post-build phase for API..."
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: 'packages/api/dist'
  name: api-build-artifact

cache:
  paths:
    - 'packages/api/node_modules/**/*'

