version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing phase..."
      - echo "Node version - $(node --version)"
      - echo "NPM version - $(npm --version)"
      
  pre_build:
    commands:
      - echo "Starting Web Build Phase..."
      - echo "Build started on $(date)"
      - echo "Current directory - $(pwd)"
      - ls -la
      - echo "Navigating to packages/web..."
      - cd packages/web
      - pwd
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps
      - echo "Dependencies installed successfully"
      - echo "Verifying TypeScript installation..."
      - npx tsc --version
      
  build:
    commands:
      - echo "Building Web Application..."
      - cd packages/web
      - echo "Running build with npx..."
      - npx tsc && npx vite build
      - echo "Build completed, checking output..."
      - ls -la dist/
      - echo "Listing dist contents..."
      - find dist -type f
      - echo "Web build completed successfully"
      
  post_build:
    commands:
      - echo "Post-build phase for Web..."
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: 'packages/web/dist'
  name: web-build-artifact

cache:
  paths:
    - 'packages/web/node_modules/**/*'

