version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing phase..."
      - echo "Node version - $(node --version)"
      - echo "NPM version - $(npm --version)"
      
  pre_build:
    commands:
      - echo "Starting Web Build Phase..."
      - echo "Build started on $(date)"
      - echo "Current directory - $(pwd)"
      - echo "Listing root directory contents..."
      - ls -la
      - echo "Checking for packages directory..."
      - test -d packages && echo "packages/ exists" || echo "packages/ NOT FOUND"
      - test -d packages/web && echo "packages/web/ exists" || echo "packages/web/ NOT FOUND"
      - echo "Full directory tree (first 2 levels)..."
      - find . -maxdepth 2 -type d
      - echo "Installing dependencies for Web..."
      - cd packages/web && npm install --legacy-peer-deps
      - echo "Dependencies installed successfully"
      
  build:
    commands:
      - echo "Building Web Application..."
      - echo "Running TypeScript compiler..."
      - cd packages/web && ./node_modules/.bin/tsc
      - echo "TypeScript compilation completed"
      - echo "Running Vite build..."
      - cd packages/web && ./node_modules/.bin/vite build
      - echo "Build completed, checking output..."
      - cd packages/web && ls -la dist/
      - echo "Listing dist contents..."
      - cd packages/web && find dist -type f
      - echo "Web build completed successfully"
      
  post_build:
    commands:
      - echo "Post-build phase for Web..."
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: 'packages/web/dist'
  name: web-build-artifact

cache:
  paths:
    - 'packages/web/node_modules/**/*'

