version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing phase..."
      - echo "Node version - $(node --version)"
      - echo "NPM version - $(npm --version)"
      
  pre_build:
    commands:
      - echo "Starting API Build Phase..."
      - echo "Build started on $(date)"
      - echo "Current directory - $(pwd)"
      - echo "Listing root directory contents..."
      - ls -la
      - echo "Checking for packages directory..."
      - test -d packages && echo "packages/ exists" || echo "packages/ NOT FOUND"
      - test -d packages/api && echo "packages/api/ exists" || echo "packages/api/ NOT FOUND"
      - echo "Full directory tree (first 2 levels)..."
      - find . -maxdepth 2 -type d
      - echo "Installing dependencies for API..."
      - cd packages/api && npm install --legacy-peer-deps
      - echo "Dependencies installed successfully"
      - echo "Generating Prisma client..."
      - cd packages/api && ./node_modules/.bin/prisma generate
      - echo "Prisma client generated successfully"
      
  build:
    commands:
      - echo "Building API Application..."
      - echo "Running TypeScript compiler..."
      - cd packages/api && ./node_modules/.bin/tsc
      - echo "Build completed, checking output..."
      - cd packages/api && ls -la dist/
      - echo "Listing dist contents..."
      - cd packages/api && find dist -type f | head -20
      - echo "API build completed successfully"
      
  post_build:
    commands:
      - echo "Post-build phase for API..."
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: 'packages/api/dist'
  name: api-build-artifact

cache:
  paths:
    - 'packages/api/node_modules/**/*'

