version: 0.2

env:
  variables:
    GIT_CLONE_DEPTH: 0

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing phase..."
      - echo "Node $(node --version), npm $(npm --version)"

  pre_build:
    commands:
      - echo "Starting API Build Phase..."
      - echo "Build started on $(date)"
      - echo "Current directory - $(pwd)"
      - echo "Listing root directory contents..."
      - ls -la
      - echo "Checking for packages/api directory..."
      - test -d packages/api || (echo "ERROR - packages/api/ NOT FOUND" && exit 1)
      - echo "✓ packages/api/ exists"
      - echo "Installing dependencies for API..."
      - npm install --prefix packages/api --include=dev --legacy-peer-deps
      - echo "✓ Dependencies installed successfully"
      - echo "Verifying TypeScript installation..."
      - test -f packages/api/node_modules/.bin/tsc && echo "✓ tsc found" || (echo "ERROR - tsc not found" && exit 1)
      - echo "Verifying Prisma installation..."
      - test -f packages/api/node_modules/.bin/prisma && echo "✓ prisma found" || (echo "ERROR - prisma not found" && exit 1)
      - echo "Generating Prisma client..."
      - cd packages/api && npx prisma generate
      - echo "✓ Prisma client generated successfully"
      - echo "Verifying Prisma client was generated..."
      - test -d packages/api/node_modules/@prisma/client && echo "✓ @prisma/client generated" || (echo "ERROR - Prisma client not generated" && exit 1)

  build:
    commands:
      - echo "Building API Application..."
      - echo "Running TypeScript compiler..."
      - npx --prefix packages/api tsc -p packages/api/tsconfig.json
      - echo "✓ TypeScript compilation completed"
      - echo "Verifying dist folder was created..."
      - test -d packages/api/dist || (echo "ERROR - dist/ folder not created" && exit 1)
      - echo "✓ dist/ folder exists"
      - echo "Listing dist contents..."
      - ls -la packages/api/dist/
      - find packages/api/dist -type f | head -20
      - echo "✓ API build completed successfully"

  post_build:
    commands:
      - echo "Post-build phase for API..."
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: 'packages/api/dist'
  name: api-build-artifact

cache:
  paths:
    - 'packages/api/node_modules/**/*'
